### PR TITLE
BTC instead of Sats on Stats For Nerds

### PR DESCRIPTION
**Pull request by ibertario**
In the "Stats For Nerds" we have now:

image

With this pretty good amount of daily volume, is better to have both amounts denominated in BTC:

image

This PR tries to solve that. Can't test but only two minor changes.

### CODE REVIEW

**Comment by Reckless-Satoshi** [comment]
Awesome!! I have not tested, but it looks like this PR should work!

Are you sure about this upgrade, though? Daily amounts are always going to be much smaller than lifetime amounts. So it makes sense to have BTC for lifetime, yet it also makes sense to have Sats for days with low trade volumes (for example, a few days ago the trade volume was only 200.000 Sats).

I propose, we pick a unit (either BTC or Sats). And then, implement a clickable action, so when the unit is clicked, the UI rotates units and multiplies or divides by 100000000.

**Comment by ibertario** [comment]
> Daily amounts are always going to be much smaller than lifetime amounts. So it makes sense to have BTC for lifetime, yet it also might be nice to have Sats for those days with low trade volumes (for example, a few days ago the trade volume was only 200.000 Sats).

Well, talking about stats, amounts with the same denomination looks better, especially when they are very close.

I think that for a Bitcoin amount BTC is easy to look (especially for Nerds).

> I propose, we pick a unit (either BTC or Sats). And then, implement a clickable action, so when the number is clicked, the UI rotates units and multiplies or divides by 100000000.

That's beyond my current dev capabilities, but definitely can be good to show a button to exchange or a tooltip with the other option.

**Comment by ibertario** [comment]
_PS: A button present in all UI that exchange between both BTC<>Sats can be (crazy?) valuated for the future._

**Comment by ibertario** [comment]
> Daily amounts are always going to be much smaller than lifetime amounts. So it makes sense to have BTC for lifetime, yet it also might be nice to have Sats for those days with low trade volumes (for example, a few days ago the trade volume was only 200.000 Sats).

Some options to valuate...

* Add 1 week
* Last 100 or 1000 blocks stats
* Little graph with 4 points from the start
* Choice one good % increase (trades, Robots, medium sats trade...)

**Comment by ibertario** [comment]
This can be merged! As we can see 24h volume is increasing...

image

We can add later another metric:

> Some options to minimize the divergence...
> 
>     * Add 1 week
> 
>     * Last 100 or 1000 blocks stats
> 
>     * Little graph with 4 points from the start
> 
>     * Choice one good % increase (trades, Robots, medium sats trade...)

**Comment by Reckless-Satoshi** [comment]
Merging as is. I am still looking forward to have some free time for a full revamp of the summarizing stats :)

**Pull request merged**
