### PR TITLE
Update es.json

### PR DESCRIPTION
**Pull request by ibertario**
Consolidate the last en.js changes before translation.

### CODE REVIEW

**Comment by Reckless-Satoshi** [comment]
Hey @ibertario thanks for contributing! 

There is at least 2 contributors working on `es.json` as far as I know.
@mamifiero did a part of the translation to Spanish a few days ago (https://github.com/mamifiero/robosats/blob/mamifiero-robosats-frontend-src-locales/frontend/src/locales/es.json) then @decentralizedb picked up the work. You can coordinate with him in this message thread to pick up the work left and review the translations made.

**Comment by decentralizedb** [comment]
> Hey @ibertario thanks for contributing!
> 
> There is at least 2 contributors working on `es.json` as far as I know. @mamifiero did a part of the translation to Spanish a few days ago (https://github.com/mamifiero/robosats/blob/mamifiero-robosats-frontend-src-locales/frontend/src/locales/es.json) then @decentralizedb picked up the work. You can coordinate with him in this message thread to pick up the work left and review the translations made.

Hello @ibertario, translation is finished, but maybe you could help by reviewing it.
Here's the last part, from line 212 onwards:

https://github.com/MonkyCrazy/robosats/blob/main/frontend/src/locales/es.json

**Comment by Reckless-Satoshi** [comment]
> Here's the last part, from line 212 onwards:
> 
> https://github.com/MonkyCrazy/robosats/blob/main/frontend/src/locales/es.json

Awesome! Since this is not a fork of @mamifiero's progress it will be hard to keep the right contributor attribution. Could you fork @mamifiero's translation progress, and  then replace the lines 212 onward for your translation. We can then open a PR with the work done so far so @ibertario can review it :)

**Comment by mamifiero** [comment]
I'm afraid some corrections need to be made. Some misspelling (no worries, it happens to all of us) and some lines translated too literally. Hopefully @ibertario can review the whole thing since quite probably my part needs some corrections as well.

**Comment by decentralizedb** [comment]
> I'm afraid some corrections need to be made. Some misspelling (no worries, it happens to all of us) and some lines translated too literally. Hopefully @ibertario can review the whole thing since quite probably my part needs some corrections as well.

As @Reckless-Satoshi suggested, we forked @mamifiero and worked there, now it's all in this url:

https://github.com/MonkyCrazy/robosats/tree/main/frontend/src/locales

**Comment by ibertario** [comment]
Sorry but I didn't saw any PR so...

At the moment @Reckless-Satoshi validates that branch so I can close this PR and use that one to fix few inconsistencies and bugs, as well as complete a small style guide.

Anyway, the work will be a small percentaje of what I was planning, thank you @mamifiero and @decentralizedb !

**Comment by Reckless-Satoshi** [comment]
> At the moment @Reckless-Satoshi validates that branch so I can close this PR and use that one to fix few inconsistencies and bugs, as well as complete a small style guide.

Hey @ibertario , new branch with the work of @decentralizedb and @mamifiero is here https://github.com/Reckless-Satoshi/robosats/tree/spanish-translation 

It is running in the development node, so you can have a look at how the translation looks here:
http://robodevs7ixniseezbv7uryxhamtz3hvcelzfwpx3rvoipttjomrmpqd.onion (if needed you can interact with it with a testnet wallet if needed). Just let me know if you commit changes and want to see how they look in the platform.

I will be fixing the UI to dynamically fit the different text sizes more gracefully where possible.

**Comment by Reckless-Satoshi** [comment]
En cuanto a la traducción: se lee muy robótico (badum-tshhh xD). Hace falta un repaso grande para que sea lenguaje más común y cercano. Muchas traducciones son estrictamente palabra a palabra las frases en inglés y pueden ni tener sentido en español.

**Comment by ibertario** [comment]
I'll try to made a small document with common words and phrases to make the translations more consistent.

Now working in the spanish translation into the tree and will submit a PR when it's done! Let me some time but I want to get all the details done this week.

**Pull request closed without merging**
