### PR TITLE
Add Traditional Chinese language locale

### PR DESCRIPTION
**Pull request by ra5pvt1n**
## What does this PR do?
Add zh-tr.json to frontend/static/locales

Add zh-si.json to frontend/static/locales

Modify en.json to add "Join Robosats Portuguese speaking community!" key-value pair
## Checklist before merging
- [x] If it's a frontend feature, I have ran prettier `cd frontend; npm run format`. If it's a mobile app feature I ran `cd mobile; npm run format`.

### CODE REVIEW

**Comment by Reckless-Satoshi** [comment]
Super valuable contribution! :rocket:

Very appreciated if someone has the time to shortly review the work of @ra5pvt1n

**Comment by Reckless-Satoshi** [comment]
Hey @ra5pvt1n , we are going to be merging as is. We'll have time to discover some typos and fix them later on :)

Please, let's make this the first rewarded translation contribution, submit an invoice from a proxy node and a long expiration time for 40K Sats.

**Comment by ra5pvt1n** [comment]
Hey @Reckless-Satoshi that's awesome. I have been looking for a reviewer and should be able to find one relatively soon. Thanks for the sats, much love :) Invoice below. 

LNBC400U1P35328APP57C6TVN3M99EJPNQ77FDZ5WLH2H0UL9R9HZKNH89SC5GSJQPTQCLSDQQCQZPGXQYPR9QSP5GFYAFLM4LC698Y25WS4RTKH00KFW3TGGVGSG5YL3E6C5XDAMDTJQ9QYYSSQUD3053K6DMFYACM2XX4QDV9R79K5YJ8FS9WL3QJMKYQ59GUTS7D307PVFSMJEUQV8UF2YTH7VK3LLDAE8F0G9K98P6ZK2UEAALWH6YSQYJLCDT

**Comment by Reckless-Satoshi** [comment]
> LNBC400U1P35328APP57C6TVN3M99EJPNQ77FDZ5WLH2H0UL9R9HZKNH89SC5GSJQPTQCLSDQQCQZPGXQYPR9QSP5GFYAFLM4LC698Y25WS4RTKH00KFW3TGGVGSG5YL3E6C5XDAMDTJQ9QYYSSQUD3053K6DMFYACM2XX4QDV9R79K5YJ8FS9WL3QJMKYQ59GUTS7D307PVFSMJEUQV8UF2YTH7VK3LLDAE8F0G9K98P6ZK2UEAALWH6YSQYJLCDT

Sorry did not catch it in time. Invoice has expired. Could you post a new one and ping me in the Matrix developers group?

**Comment by ra5pvt1n** [comment]
LNBC400U1P354XKEPP5DD0S5LALDHAVR508C8KKS8DH203MYV85S6MVDZFH8AZNRE5CY6JQDPQ23EXZMNND3SHG6T0DCS9YMMZDAEKZARNCQZPGXQYDHWSSP5JWH6YNNQK5R40UFT2HERP9XVLWGV6ZF9VD5X6442NKQ4K98CYJ5Q9QYYSSQVQHAGUJWLW2DSZDJG9RUTSMPKNP7XTZADKJ4LM6DDWRGM5NAUYLS0EHAPADTPNV0KH2UYQJ3QRTJ4PCEH5SQXNU8LJSSC3HZYRSW84QQXS0VFE

**Comment by Reckless-Satoshi** [comment]
> LNBC400U1P354XKEPP5DD0S5LALDHAVR508C8KKS8DH203MYV85S6MVDZFH8AZNRE5CY6JQDPQ23EXZMNND3SHG6T0DCS9YMMZDAEKZARNCQZPGXQYDHWSSP5JWH6YNNQK5R40UFT2HERP9XVLWGV6ZF9VD5X6442NKQ4K98CYJ5Q9QYYSSQVQHAGUJWLW2DSZDJG9RUTSMPKNP7XTZADKJ4LM6DDWRGM5NAUYLS0EHAPADTPNV0KH2UYQJ3QRTJ4PCEH5SQXNU8LJSSC3HZYRSW84QQXS0VFE

15f5f72e4ca65840598b9e4980372fa4d3f0dc061143de21fe30edf4f199fde2

**Pull request merged**
