### PR TITLE
Update 13-fees.md

### PR DESCRIPTION
**Pull request by okada-blue**
## What does this PR do?
Add documentation for "Fees"

## Checklist before merging
- [ ] Make sure you have installed and initialized [pre-commit](https://pre-commit.com). `pip install pre-commit` and `pre-commit install`

### CODE REVIEW

**Comment by redphix** [comment]
Hey @okada-blue great work on this. It reads perfectly from start to finish! Left a review about the table though — I don't understand what it tries to convey.

> how can I go about including the mining fee and swap fee (on-chain payouts)? For example, where I have:
> 
> `payout_amount = trade_sats + fee_sats`
> 
> would I just "add" the mining fee and swap fee, if applicable, perhaps like so:
> 
> `payout_amount = trade_sats + fee_sats (+ fee_mining + fee_swap)`

I think you replaced '-' with a '+' here in these examples. It should be:

`payout_amount = trade_sats - fee_sats`

and yes, you are correct about the mining and swap fee being deducted from the payout. You can have that mentioned in the External Fees section itself, instead of making a new section:

`payout_amount = trade_sats - fee_sats - fee_mining - fee_swap`

**Comment by Reckless-Satoshi** [comment]
Hey @okada-blue . I also had a similar thought to what @redphix  had when reading it. Merging this one once ready after these minor fixes.

**Comment by Reckless-Satoshi** [comment]
> I suppose I'll leave the verbiage for explicit pricing method when it becomes a feature again?

Great, most likely we will see this feature back only once the RoboSats PRO frontend is ready.

> added fees for lnproxy based on telegram comments

Very useful too!

Merging as is. Please send an invoice for 30K Sats (let's up by 50% the reward to contributing Docs).

**Comment by Reckless-Satoshi** [comment]
> lnbc300u1p3ane6wpp55w6wlmjhjfhf8qe9g3tvr2ewrxmx3jnhxranmdls5nxj9npcr9ysdqu2askcmr9wssx7e3q2dshgmmndp5scqzpgxqyz5vqsp5dy3ylcetqvat5hv8kkhpaeyynt4lu98memphzqeaf0ydle4r7q5s9qyyssqv5756kuxzrwkgx765nz28f8945c83syhn5jervj2975zcshhn49k7v8z9wfqg3uhyh3sc66kgchle456hahwtlnmcw6nhh3luv3j3kspuzx77n

1d34fe630343f6bf6e276f4b49d100740183d1a54a2d050af1310ed3980e36e3

**Pull request merged**
