### PR TITLE
The Japanese translation for RoboSats

### PR DESCRIPTION
**Pull request by aaroniumii**
This PR adds the japanese translation of RoboSats.
Arigato.

### CODE REVIEW

**Comment by Reckless-Satoshi** [comment]
Hey @aaroniumii , this is amazing!

We are going to merge as is so this is ready on v0.4.4. If someone was to find some phrases can be improved later on, we fix them once the translation is live.

Please send a lightning invoice from a proxy wallet for 50K Sats (>24h expiration time) as a small tip from the devfund for this top contribution.

**Comment by aaroniumii** [comment]
Thank you very much for accepting.
It is an honor to be able to collaborate, if not with code, at least with a translation.
I will also be ready to make the necessary adjustments that users who cannot edit on Github may find.

lnbc500u1pjy6tgxpp5y4xkqsw4huxt93dsrfa4zfgkzny82kpdkmf6usdkjyjnkzlqxm5qdqaf3hkueeqd35hvefq2fhkym6nv968xcqzpgxqyz5vqsp5wt88ayk7yddsk9r4039zsxwr2qfs933jqxe2ehrptlgl3z7uhquq9qyyssq5jyme6dmylmdxrpcyqgdsmwzx6pcq42vnwzcxujjx0lkuw7lgrsyq9rfx58kn8f4dkvaz45tvp399500umxev0gytcvcqp35qgpxw5cqkljmmt

**Comment by Reckless-Satoshi** [comment]
> lnbc500u1pjy6tgxpp5y4xkqsw4huxt93dsrfa4zfgkzny82...

Hey again :) Unfortunately the invoice expired on me before I could get around to send the Sats. Can you send a new one?

**Comment by aaroniumii** [comment]
Thank you very much for that despite how busy you must be. 🙇

lnbc500u1pj9paclpp5ej48p88mgslsj98e3nzex9yj2tawdayna9hg32n5geudvkh9222sdpyf3hkueeqd35hvefq2fhkym6nv968xg8zn2sscqzpgxqyz5vqsp5g4x7n96pxjm4gwrclm7t0z0hltgyzt4fzrmtge2esx7teyymh9js9qyyssqvpetm4k27p49ntzyye3gfenwtpatlrm97hj3l5kxj2xxj33mazjr6gc7anrzs39ka8aetktyf9qa7vyrjly4tqq6z65fayrxzv0ktjqpgx72pr

**Comment by Reckless-Satoshi** [comment]
> lnbc500u1pj9paclpp5ej48p88mgslsj98e3nzex9yj2tawdayna9hg32n5geudvkh9222sdpyf3hkueeqd35hvefq2fhkym6nv968xg8zn2sscqzpgxqyz5vqsp5g4x7n96pxjm4gwrclm7t0z0hltgyzt4fzrmtge2esx7teyymh9js9qyyssqvpetm4k27p49ntzyye3gfenwtpatlrm97hj3l5kxj2xxj33mazjr6gc7anrzs39ka8aetktyf9qa7vyrjly4tqq6z65fayrxzv0ktjqpgx72pr

5c8836e13aa92e90686a1ed5854ec02b21bac9eae48989201264b0e670a16793

**Pull request merged**
