### PR TITLE
pl.json

### PR DESCRIPTION
**Pull request by valladolidBTCpol**

### CODE REVIEW

**Comment by valladolidBTCpol** [comment]
polish translation

**Comment by Reckless-Satoshi** [comment]
Hey @valladolidBTCpol, really awesome you opened this PR for a Polish translation! Ping me when you think it is ready for review and merge :D

**Comment by valladolidBTCpol** [comment]
@Reckless-Satoshi I think it's done

**Comment by Reckless-Satoshi** [comment]
I will be testing and merging later today. Unfortunately, I do not think we have anyone able to review your work in Polish. :)

**Comment by Reckless-Satoshi** [comment]
@valladolidBTCpol 
Thanks for the huge sprint to get this translation done!! 👏👏👏

You can see it running in [Testnet](http://[testnet.robosats.com/](http://robotestagw3dcxmd66r4rgksb4nmmr43fh77bzn2ia2eucduyeafnyd.onion/)) (it is sometimes down).

If you could, take a look on the places where the longer texts break the UI. For example, the homepage buttons become double line in the mobile view. Also some headers of the contract box become double line (you can create a dummy order to check the contract box). Probably some cannot be fixed, but maybe you find an easy way to make these shorter. Translations often do not need to be literal. For example "Make order" and "View book" buttons could simply be "make" and "take" if that makes the new language fit.

**Comment by valladolidBTCpol** [comment]
@Reckless-Satoshi Perfect.
I'll get with it on Saturday and Sunday

**Pull request merged**
