### PR TITLE
Annoy black

### PR DESCRIPTION
**Pull request by redphix**
## What does this PR do?
annoy black

## Checklist before merging
- [ ] If it's a frontend feature, I have ran prettier `cd frontend; npm run format`. If it's a mobile app feature I ran `cd mobile; npm run format`.

### CODE REVIEW

**Comment by redphix** [comment]
Okay nice. The flake8 lints work with annotations.

**Comment by redphix** [comment]
@Reckless-Satoshi 
But the black auto-fix should only work when you either
1. Open a PR yourself
2. push to main

**Comment by Reckless-Satoshi** [comment]
> looks fine for now. What do you think?

I think it's a way better set up than what we had before! :smile: Thank you very much for getting this done :rocket:

**Comment by redphix** [comment]
Final test I guess -- merging this should run the auto-fix and commit it to main branch.

**Comment by Reckless-Satoshi** [comment]
> Final test I guess -- merging this should run the auto-fix and commit it to main branch.

Merged. Auto-fix did not add a new commit, possibly because it also needs `on.pull_request` event as trigger. In any case, do we want auto fix commits? It is probably enough with PR checks. Also a bit scary the bot committing changes to main :D

**Comment by redphix** [comment]
@Reckless-Satoshi Yes, I was also having second thoughts about it :D. A bot commit changes to main is definitely an uncomfortable feeling. I guess we don't autofix then -- commit annotations are more that enough. The auto-fixing part can be documented/enforced using pre-commit.

**Comment by redphix** [comment]
@Reckless-Satoshi Oh the reason It didn't work is because of this - https://github.com/redphix/robosats/blob/1dea4e73b6410ca741c85a4b6c4b8ab2e2649bcb/.github/workflows/py-linter.yml#L36

**Pull request merged**
